name: Build
on:
   push:
     branches: [ 'v2.0' ]
     paths-ignore: [ 'docs/**' ]

permissions: write-all

jobs:
  build:
    runs-on: macos-latest
    env:
      SLN_FILE: Fabulous-NoSamples.sln
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.300
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build --no-restore --configuration Release ${SLN_FILE}
    - name: Test
      run: dotnet test --no-build --configuration Release ${SLN_FILE}
    - name: Pack
      run: |
        sed -i bak "s/FABULOUS_PKG_VERSION/2.0.0-nightly-${GITHUB_RUN_ID}/g" "templates/content/*/.template.config/template.json"
        dotnet pack --configuration Release --output nupkgs --version-suffix "nightly-${GITHUB_RUN_ID}" ${SLN_FILE}
        dotnet pack -p:IsNightlyBuild=true --configuration Release --output nupkgs --version-suffix "nightly-${GITHUB_RUN_ID}" templates/Fabulous.XamarinForms.Templates.proj
    - name: Push
      run: |
        dotnet nuget push "nupkgs/*.nupkg" -s https://nuget.pkg.github.com/fsprojects/index.json -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
