name: .NET
on:
   push:
     branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    env:
      SLN_FILE: Fabulous-NoSamples.sln
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.200
    - name: Set GitHub PAT for NuGet
      run: |
        cp nuget.config.example nuget.config
        dotnet nuget update source fabulousfx -u USERNAME -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Install dotnet workload
      run: dotnet workload install ios android
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build --no-restore --configuration Release ${SLN_FILE}
    - name: Test
      run: dotnet test --no-build --configuration Release ${SLN_FILE}
    - name: Pack
      run: |
        sed -i bak "s/FABULOUS_PKG_VERSION/2.0.0-nightly-${GITHUB_RUN_ID}/g" "templates/content/blank/.template.config/template.json"
        dotnet pack --configuration Release --output nupkgs --version-suffix "nightly-${GITHUB_RUN_ID}" ${SLN_FILE}
        dotnet pack --configuration Release --output nupkgs --version-suffix "nightly-${GITHUB_RUN_ID}" templates/Fabulous.XamarinForms.Templates.proj
    - name: Push
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/TimLariviere/index.json --name timlariviere
        dotnet nuget push "nupkgs/*.nupkg" --source timlariviere --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
