name: .NET
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLN_FILE: Fabulous-NoSamples.sln
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Check code formatting
      run: |
        dotnet tool restore
        dotnet fantomas --check -r src
        dotnet fantomas --check -r samples
        dotnet fantomas --check -r templates
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build --no-restore --configuration Release ${SLN_FILE}
    - name: Test
      run: dotnet test --no-build --configuration Release ${SLN_FILE}
