name: Pull Request
on: pull_request

env:
  SLN_FILE: Fabulous.sln

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Check code formatting
      run: |
        dotnet tool restore
        dotnet fantomas --check -r src samples templates
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build ${SLN_FILE} --no-restore --configuration Release
    - name: Test
      run: dotnet test ${SLN_FILE} --no-build --configuration Release