name: Pull Request
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Check code formatting
      run: |
        dotnet tool restore
        dotnet fantomas --check -r src samples templates

  xf:
    name: Fabulous.XamarinForms
    runs-on: macos-latest
    env:
      SLN_FILE: Fabulous.XamarinForms.NoSamples.sln
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build ${SLN_FILE} --no-restore --configuration Release
    - name: Test
      run: dotnet test ${SLN_FILE} --no-build --configuration Release

  maui:
    name: Fabulous.MauiControls
    runs-on: macos-12
    env:
      SLN_FILE: Fabulous.MauiControls.NoSamples.sln
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dotnet workload
      run: dotnet workload install maui --from-rollback-file .github/workflows/maui-WorkloadManifest.json
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build ${SLN_FILE} --no-restore --configuration Release
    - name: Test
      run: dotnet test ${SLN_FILE} --no-build --configuration Release
